### ISSUE TITLE
Explosion on first sweep

### ISSUE THREAD

**Issue by VCnockaert** [JeroenVerberneDemcon/DecodeDemcon3#1]
## Issue

Running the code

```
mf = MineField(width=3, height=3, number_of_mines=8)
print(mf.sweep_cell(column=2, row=1))
```

results in a `mineField.ExplosionException` on the first sweep. According to the comments, this is unwanted behavior.

## Solution

https://github.com/JeroenVerberneDemcon/DecodeDemcon3/blob/f09e596bd3d78b4c8408e097322636c210a741a6/mineField.py#L65

`(row, column)` should be changed to `(column, row)` to match the order as used in the rest of the program.

**Comment by JeroenVerberneDemcon** [comment]
Thank you for bringing this to our attention! A solution has been implemented.
