### ISSUE TITLE
Index error during sweeping

### ISSUE THREAD

**Issue by VCnockaert** [JeroenVerberneDemcon/DecodeDemcon3#2]
## Issue

Running the code

```
mf = MineField(width=3, height=5, number_of_mines=14)
print(mf.sweep_cell(column=2, row=2))
```

results in a `IndexError: list index out of range`.

In addition, running the code

```
mf = MineField(width=5, height=3, number_of_mines=14)
print(mf.sweep_cell(column=2, row=2))
```

returns `4`, which is incorrect. The correct number of neighboring mines is 5.

## Solution

https://github.com/JeroenVerberneDemcon/DecodeDemcon3/blob/f09e596bd3d78b4c8408e097322636c210a741a6/mineField.py#L115

`(column < (self.__height - 1))` should be changed to `(column < (self.__width - 1))` as the *column* is the index bound by *width* and not by *height*.

**Comment by JeroenVerberneDemcon** [comment]
Thank you for bringing this to our attention! A solution has been implemented.
